#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#sonata_user_admin_security:
#    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
#    prefix: /admin
#
#sonata_user_admin_resetting:
#    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
#    prefix: /admin/resetting
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
#    prefix:   /api/doc    